export type Category = {
  id: number;
  parentId: number | null;
  label: string;
  slug: string;
  isLeaf: boolean;
  level: number;
  children: Category[];
};

export const Categories: Category[] = [
  {
    id: 1,
    parentId: null,
    label: "Woman's Fashion",
    slug: "womens-fashion",
    isLeaf: false,
    level: 0,
    children: [
      {
        id: 2,
        parentId: 1,
        label: "Clothing",
        slug: "womens-clothing",
        isLeaf: false,
        level: 1,
        children: [
          {
            id: 3,
            parentId: 2,
            label: "Dresses",
            slug: "womens-dresses",
            isLeaf: true,
            level: 2,
            children: [],
          },
          {
            id: 4,
            parentId: 2,
            label: "Tops & Blouses",
            slug: "womens-tops",
            isLeaf: true,
            level: 2,
            children: [],
          },
          {
            id: 5,
            parentId: 2,
            label: "Jeans",
            slug: "womens-jeans",
            isLeaf: true,
            level: 2,
            children: [],
          },
          {
            id: 6,
            parentId: 2,
            label: "Jackets & Coats",
            slug: "womens-outerwear",
            isLeaf: true,
            level: 2,
            children: [],
          },
        ],
      },
      {
        id: 7,
        parentId: 1,
        label: "Shoes",
        slug: "womens-shoes",
        isLeaf: false,
        level: 1,
        children: [
          {
            id: 8,
            parentId: 7,
            label: "Heels",
            slug: "heels",
            isLeaf: true,
            level: 2,
            children: [],
          },
          {
            id: 9,
            parentId: 7,
            label: "Sneakers",
            slug: "sneakers",
            isLeaf: true,
            level: 2,
            children: [],
          },
          {
            id: 10,
            parentId: 7,
            label: "Flats",
            slug: "flats",
            isLeaf: true,
            level: 2,
            children: [],
          },
          {
            id: 11,
            parentId: 7,
            label: "Boots",
            slug: "boots",
            isLeaf: true,
            level: 2,
            children: [],
          },
        ],
      },
      {
        id: 12,
        parentId: 1,
        label: "Accessories",
        slug: "womens-accessories",
        isLeaf: false,
        level: 1,
        children: [
          {
            id: 13,
            parentId: 12,
            label: "Bags",
            slug: "bags",
            isLeaf: true,
            level: 2,
            children: [],
          },
          {
            id: 14,
            parentId: 12,
            label: "Jewelry",
            slug: "jewelry",
            isLeaf: true,
            level: 2,
            children: [],
          },
          {
            id: 15,
            parentId: 12,
            label: "Watches",
            slug: "watches",
            isLeaf: true,
            level: 2,
            children: [],
          },
          {
            id: 16,
            parentId: 12,
            label: "Scarves",
            slug: "scarves",
            isLeaf: true,
            level: 2,
            children: [],
          },
        ],
      },
    ],
  },

  {
    id: 17,
    parentId: null,
    label: "Men's Fashion",
    slug: "mens-fashion",
    isLeaf: false,
    level: 0,
    children: [
      {
        id: 18,
        parentId: 17,
        label: "Clothing",
        slug: "mens-clothing",
        isLeaf: false,
        level: 1,
        children: [
          {
            id: 19,
            parentId: 18,
            label: "T-Shirts & Shirts",
            slug: "mens-shirts",
            isLeaf: true,
            level: 2,
            children: [],
          },
          {
            id: 20,
            parentId: 18,
            label: "Jeans",
            slug: "mens-jeans",
            isLeaf: true,
            level: 2,
            children: [],
          },
          {
            id: 21,
            parentId: 18,
            label: "Suits",
            slug: "mens-suits",
            isLeaf: true,
            level: 2,
            children: [],
          },
          {
            id: 22,
            parentId: 18,
            label: "Hoodies & Jackets",
            slug: "mens-hoodies",
            isLeaf: true,
            level: 2,
            children: [],
          },
        ],
      },
      {
        id: 23,
        parentId: 17,
        label: "Shoes",
        slug: "mens-shoes",
        isLeaf: false,
        level: 1,
        children: [
          {
            id: 24,
            parentId: 23,
            label: "Sneakers",
            slug: "mens-sneakers",
            isLeaf: true,
            level: 2,
            children: [],
          },
          {
            id: 25,
            parentId: 23,
            label: "Formal Shoes",
            slug: "mens-formal-shoes",
            isLeaf: true,
            level: 2,
            children: [],
          },
          {
            id: 26,
            parentId: 23,
            label: "Boots",
            slug: "mens-boots",
            isLeaf: true,
            level: 2,
            children: [],
          },
          {
            id: 27,
            parentId: 23,
            label: "Sandals",
            slug: "mens-sandals",
            isLeaf: true,
            level: 2,
            children: [],
          },
        ],
      },
      {
        id: 28,
        parentId: 17,
        label: "Accessories",
        slug: "mens-accessories",
        isLeaf: false,
        level: 1,
        children: [
          {
            id: 29,
            parentId: 28,
            label: "Watches",
            slug: "mens-watches",
            isLeaf: true,
            level: 2,
            children: [],
          },
          {
            id: 30,
            parentId: 28,
            label: "Belts",
            slug: "mens-belts",
            isLeaf: true,
            level: 2,
            children: [],
          },
          {
            id: 31,
            parentId: 28,
            label: "Wallets",
            slug: "mens-wallets",
            isLeaf: true,
            level: 2,
            children: [],
          },
          {
            id: 32,
            parentId: 28,
            label: "Hats & Caps",
            slug: "mens-hats",
            isLeaf: true,
            level: 2,
            children: [],
          },
        ],
      },
    ],
  },

  {
    id: 33,
    parentId: null,
    label: "Electronics",
    slug: "electronics",
    isLeaf: true,
    level: 0,
    children: [],
  },
  {
    id: 34,
    parentId: null,
    label: "Home & Lifestyle",
    slug: "home-lifestyle",
    isLeaf: true,
    level: 0,
    children: [],
  },
  {
    id: 35,
    parentId: null,
    label: "Medicine",
    slug: "medicine",
    isLeaf: true,
    level: 0,
    children: [],
  },
  {
    id: 36,
    parentId: null,
    label: "Sports & Outdoor",
    slug: "sports-outdoor",
    isLeaf: true,
    level: 0,
    children: [],
  },
  {
    id: 37,
    parentId: null,
    label: "Baby's & Toys",
    slug: "baby-toys",
    isLeaf: true,
    level: 0,
    children: [],
  },
  {
    id: 38,
    parentId: null,
    label: "Groceries & Pets",
    slug: "groceries-pets",
    isLeaf: true,
    level: 0,
    children: [],
  },
  {
    id: 39,
    parentId: null,
    label: "Health & Beauty",
    slug: "health-beauty",
    isLeaf: true,
    level: 0,
    children: [],
  },
];
