import Footer from "@/_components/Footer";
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";

//Moram definirati weightove jer ne koristim varijabilni font
//Da koristim varijabilini font onda weightove ne moram definirati imam ih sve
const poppins = Poppins({
  weight: ["400", "500", "600"],
  variable: "--font-poppins",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function FeaturesLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        style={{
          display: "grid",
          height: "100vh",
          gridTemplateRows: "1fr auto",
        }}
        className={`${poppins.variable}  antialiased`}>
        <main>{children}</main>

        <Footer />
      </body>
    </html>
  );
}
